export const STORAGE_KEY = {
  USER_INFO: "USER_INFO",
  TOKEN: "TOKEN",
  RECIPE_DETAILS: "RECIPE_DETAILS",
  CURRENT_USER: "CURRENT_USER",
  FAVOURITES: "FAVOURITES",
  SUGGESTED: "SUGGESTED",
  RECIPES: "RECIPES",
  INGREDIENTS: "INGREDIENTS",
};
